services:
  app:
    build: ./
    entrypoint: /bin/sh
    command: -c "/app/wait-for-postgres.sh postgres npm run dev"
    environment:
      - NODE_ENV=development
    ports:
      - 3001:3001
    volumes:
      - ./src:/app/src
      - ./public:/app/public
    stdin_open: true
    tty: true
  
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    expose:
      - 5432
