import type { Metadata } from "next";
import { Inter } from "next/font/google";

import { GreetingProvider } from "./providers/GreetingProvider";

import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <GreetingProvider>
      <html lang="en">
        <body className={inter.className}>
          <h1>This is from the Root Layout</h1>
          {children}
        </body>
      </html>
    </GreetingProvider>
  );
}
